### ISSUE TITLE
Can't build in Cygwin: pubnub/c/libpubnub/pubnub.c:730: undefined reference to `SSL_CTX_get_cert_store'

### ISSUE THREAD

**Issue by alaughlin** [pubnub/c#10]
When attempting to build this project in Cygwin on Windows 7, I receive the above error.

Package "openssl-devel" has been installed and "ssl.h" (which does indeed contain the function) is found in  "/usr/include/openssl/"

**Comment by geremyCohen** [comment]
@alaughlin we see you closed this... were you able to find a solution on your own?  If not, please contact us at support@pubnub.com so we can learn more about the issue to get you a solution.
